### ISSUE TITLE
Example Code does not work on my machine

### ISSUE THREAD

**Issue by JAFHall** [fcdimitr/SGtSNEpi.jl#14]
I have been exploring ways to display large but sparse networks and your algorithm came up.  I have tried to use the sample code from the Graph plotting tutorial in Graphs.jl documentation (you can find that code [here](https://juliagraphs.org/Graphs.jl/dev/first_steps/plotting/)).  This code does not appear to run, and the error that Julia is telling me is occuring is an undefined variable libsgtsnepi, which as far as I can tell is only used in the c call in sgtsne.jl.

**Comment by fcdimitr** [comment]
Hello! What operating system are you using? 

The current version does not support native Windows; you can run it via the [the Windows Subsystem for Linux (WSL2)](https://learn.microsoft.com/en-us/windows/wsl/about). 

It also does not support `Arm` Macs, but you can install Intel-based Julia and emulate it via `Rosetta`.

**Comment by JAFHall** [comment]
That would be the issue - I am on Windows 11.  Thank you very much!

**Comment by fcdimitr** [comment]
Hey @JAFHall! We just released v0.4.0 which should work natively on Windows. Could you give it a try and if you have any problems, please reopen this issue. Thanks!
