### ISSUE TITLE
FLANN dependancy issue

### ISSUE THREAD

**Issue by Kydlaw** [fcdimitr/SGtSNEpi.jl#9]
Hi,

Due to an issue on FLANN side (see https://github.com/wildart/FLANN.jl/issues/25), this package do not work anymore :/

Would you have any idea for a work-around by any chance?

**Comment by fcdimitr** [comment]
Thank you for raising this issue!

We will add a new version that optionally uses FLANN, if it is already added on the user’s project. 

I will upload a pull request and let you know to test it on your side.

**Comment by fcdimitr** [comment]
@Kydlaw try out #10 and let me know if it resolves your issue!

**Comment by Kydlaw** [comment]
@fcdimitr Wow! Thank you for the quick patch! I'll give it a try in the following days and come back to you!
